#!/usr/bin/env python
#design by S.W
#For auto configure RB2011

import sys
import os
import time
import pexpect

rb_ip = '192.168.88.1'
#ip = '172.16.0.254'
user = 'admin'
passwd = 'exun1234qwe'

def conf():
    telnet = pexpect.spawn('ssh  root@192.168.180.138')
    telnet.expect('root@192.168.180.138\'s password:')
    #telnet.sendline('admin')
    #telnet.expect('Password:')
    telnet.sendline('6650967a')
    telnet.expect('root@shuwei-System-Product-Name:~#')
    telnet.sendline('reboot')
#    print 'login in sucessfully'
 #   telnet.close()
    return telnet


conf()
