#!/usr/bin/env python
_metaclass_ = type

class Person:
    
    def setName(self,name):
        self.name=name
    def greet(self):
        print "Hello,word.I'm %s." % self.name

foo = Person()
foo.setName('shu wei')
foo.greet()
